export const questionsd = [{ q: "How long have you lived at your current address?", option: "" },
{
    q: "What is ownership status of your current residence?",
    option: ["none", "Rent", "Lease", "Mortgage", "Family Home", "Own"],
},
{
    q: "What type of property do you currently live in?",
    option: ["Apartment", "Townhouse", "House"],
},
{ q: "How long did you live at your previous address?", option: "" },
{
    q: "What is ownership status of your previous residence?",
    option: ["none", "Rent", "Lease", "Mortgage", "Family Home", "Own"],
},
{
    q: "What type of property did you previously live in?",
    option: ["Apartment", "Townhouse", "House"],
},
{
    q: "What is your Marital Status?",
    option: ["Single ", "Married", "Divorced"],
},
{ q: "What is your Gender?", option: ["None", "Male", "Female"] },
{ q: "How many dependents do you have?", option: "" },
{ q: "How many dependents live with you?", option: "" },
{ q: "What is your age?", option: "" },
];

export const workExperienceD = [
    {
        q: "What is your current employment status?",
        type: "dropdown",
        option: [
            "None",
            "Full-time",
            "Part-time",
            "Self Employed",
            "Contractor",
            "Unemployed",
        ]
    },
    {
        q: "What is your current employment level?",
        type: "dropdown",
        option: ['None', 'Intern',
            'Entry-Level',
            'Junior',
            'Assistant Manager',
            'Manager',
            'Senior Manager',
            'Executive',
            'VP',
            'CEO',
            'Managing Director',
            'Board Member'
        ]
    },
    {
        q: "How many years have you worked in your current position?",
        type: "numeric",
        option: ''
    },
    {
        q: "What Industry do you currently work in?",
        type: "dropdown",
        option: ['None', 'Accountancy & Finance',
            'Actuary',
            'Agriculture',
            'Banking Financial services & Insurance',
            'Beauty Hair Care Leisure & Sport',
            'Construction Architecture & Property',
            'Customer Service Call Centres & Languages',
            'Development Social & Voluntary',
            'Education Childcare & Training',
            'Energy Oil & Gas',
            'Engineering & Utilities',
            'Environmental Health & Safety',
            'Hospitality Tourism & Catering',
            'Human Resources',
            'Information Technology',
            'Legal',
            'Management',
            'Marine',
            'Marketing',
            'Medical Professionals & Healthcare',
            'Mining',
            'Procurement & Supply Chain Management',
            'Public Sector',
            'Publishing Media & Creative Arts',
            'Retailing Wholesaling & Purchasing',
            'Sales',
            'Telecoms',
            'Transport Shipping Warehousing & Automotive',
            'Travel & Airlines',
            'Working from Home'
        ],
    },
    {
        q: "What was your previous employment status?",
        type: "dropdown",
        option: ["None",
            "Full-time",
            "Part-time",
            "Self Employed",
            "Contractor",
            "Unemployed"]
    },
    {
        q: "What was your previous employment level?",
        type: "dropdown",
        option: ['None', 'Intern',
            'Entry-Level',
            'Junior',
            'Assistant Manager',
            'Manager',
            'Senior Manager',
            'Executive',
            'VP',
            'CEO',
            'Managing Director',
            'Board Member'
        ]
    },
    {
        q: "How many years have you worked in your previous position?",
        type: "numeric",
        option: ''
    },
    {
        q: "What Industry did you previously work in?",
        type: "dropdown",
        option: ['None', 'Accountancy & Finance',
            'Actuary',
            'Agriculture',
            'Banking Financial services & Insurance',
            'Beauty Hair Care Leisure & Sport',
            'Construction Architecture & Property',
            'Customer Service Call Centres & Languages',
            'Development Social & Voluntary',
            'Education Childcare & Training',
            'Energy Oil & Gas',
            'Engineering & Utilities',
            'Environmental Health & Safety',
            'Hospitality Tourism & Catering',
            'Human Resources',
            'Information Technology',
            'Legal',
            'Management',
            'Marine',
            'Marketing',
            'Medical Professionals & Healthcare',
            'Mining',
            'Procurement & Supply Chain Management',
            'Public Sector',
            'Publishing Media & Creative Arts',
            'Retailing Wholesaling & Purchasing',
            'Sales',
            'Telecoms',
            'Transport Shipping Warehousing & Automotive',
            'Travel & Airlines',
            'Working from Home'
        ]
    },
    {
        q: "What was your previous employment status?",
        type: "dropdown",
        option: ["None",
            "Full-time",
            "Part-time",
            "Self Employed",
            "Contractor",
            "Unemployed"]
    },
    {
        q: "What was your previous employment level?",
        type: "dropdown",
        option: ['None', 'Intern',
            'Entry-Level',
            'Junior',
            'Assistant Manager',
            'Manager',
            'Senior Manager',
            'Executive',
            'VP',
            'CEO',
            'Managing Director',
            'Board Member'
        ]
    },
    { q: "How many years have you worked in your previous position?", type: "numeric", option: "" },
    {
        q: "What Industry did you previously work in?",
        type: "dropdown",
        option: ['None', 'Accountancy & Finance',
            'Actuary',
            'Agriculture',
            'Banking Financial services & Insurance',
            'Beauty Hair Care Leisure & Sport',
            'Construction Architecture & Property',
            'Customer Service Call Centres & Languages',
            'Development Social & Voluntary',
            'Education Childcare & Training',
            'Energy Oil & Gas',
            'Engineering & Utilities',
            'Environmental Health & Safety',
            'Hospitality Tourism & Catering',
            'Human Resources',
            'Information Technology',
            'Legal',
            'Management',
            'Marine',
            'Marketing',
            'Medical Professionals & Healthcare',
            'Mining',
            'Procurement & Supply Chain Management',
            'Public Sector',
            'Publishing Media & Creative Arts',
            'Retailing Wholesaling & Purchasing',
            'Sales',
            'Telecoms',
            'Transport Shipping Warehousing & Automotive',
            'Travel & Airlines',
            'Working from Home'
        ]
    }
];
export const finantialQuestions = [
    { q: 'How much are you planning to borrow?', type: 'numeric', option: '' },
    { q: 'How many months are you planning to take the loan for?', type: 'numeric', option: '' },

    { q: 'Will your loan be secured or unsecured?', type: 'dropdown', option: ['Secured', 'Unsecured'] },

    { q: 'What is the value of the security?', type: 'numeric', option: '' },

    {
        q: 'What Asset will you secure your loan with?', type: 'dropdown', option: ['Financial Instruments',
            'Insurance Policy',
            'Motor Car',
            'Home',
            'Other'
        ]
    },
    {
        q: 'What is the purpose of your loan?', type: 'dropdown', option: ['Education',
            'Medical Related',
            'Home Improvement',
            'Travel',
            'Other',
            'Debt Consolidation'
        ]
    },
    { q: 'Monthly Credit Card Payment', type: 'numeric', option: '' },
    { q: 'Mortgage Payments', type: 'numeric', option: '' },
    { q: 'Car Loan Payments', type: 'numeric', option: '' },
    { q: 'Other Loan Payments', type: 'numeric', option: '' },
    { q: 'Rent Payment', type: 'numeric', option: '' },
    { q: 'How much do you spend on utilities?', type: 'numeric', option: '' },
    { q: 'Insurance Payment', type: 'numeric', option: '' },
    { q: 'How much do you spend on life insurance premiums?', type: 'numeric', option: '' },
    { q: 'Transport Expenses', type: 'numeric', option: '' },
    { q: 'Living Expenses', type: 'numeric', option: '' },
    { q: 'Education Expenses', type: 'numeric', option: '' },
    { q: 'Medical Expenses', type: 'numeric', option: '' },
    { q: 'Entertainment Expenses', type: 'numeric', option: '' },
    { q: 'Other Monthly Income', type: 'numeric', option: '' },
    { q: 'What is your Net Monthly Income?', type: 'numeric', option: '' },
    { q: 'Other Monthly Expenses', type: 'numeric', option: '' },
    { q: 'Have you ever been bankrupt?', type: 'dropdown', option: ['Yes', 'No'] },
    { q: 'How many years have passed since your bankruptcy?', type: 'numeric', option: '' },
];