export const questionsd = [
    { q: "Years living at current address", option: "" },
    {
        q: "Ownership of current residence",
        option: ["None", "Rent", "Lease", "Mortgage", "Family Home", "Own"],
    },
    {
        q: "Type of residence you currently in",
        option: ["Apartment", "Townhouse", "House"],
    },
    { q: "Years lived at previous address", option: "" },
    {
        q: "Ownership of previous residence",
        option: ["None", "Rent", "Lease", "Mortgage", "Family Home", "Own"],
    },
    {
        q: "Type of residence you previously lived in",
        option: ["Apartment", "Townhouse", "House"],
    },
    {
        q: "Marital Status",
        option: ["Single", "Married", "Divorced"],
    },
    { q: "Gender", option: ["None", "Male", "Female"] },
    {
        q: "Number of Dependents (persons you take care of financially)",
        option: "",
    },
    { q: "Number of Dependents living with you", option: "" },
    { q: "Age", option: "" },
];

export const workExperienceD = [
    {
        q: "Current Employment status",
        type: "dropdown",
        option: [
            "None",
            "Full-time",
            "Part-time",
            "Self Employed",
            "Contractor",
            "Unemployed",
        ],
    },
    {
        q: "Current Employment level",
        type: "dropdown",
        option: [
            "None",
            "Intern",
            "Entry-Level",
            "Junior",
            "Assistant Manager",
            "Manager",
            "Senior Manager",
            "Executive",
            "VP",
            "CEO",
            "Managing Director",
            "Board Member",
        ],
    },
    {
        q: "Years in current position",
        type: "numeric",
        option: "",
    },
    {
        q: "Industry you currently work in",
        type: "dropdown",
        option: [
            "None",
            "Accountancy & Finance",
            "Actuary",
            "Agriculture",
            "Banking Financial services & Insurance",
            "Beauty Hair Care Leisure & Sport",
            "Construction Architecture & Property",
            "Customer Service Call Centres & Languages",
            "Development Social & Voluntary",
            "Education Childcare & Training",
            "Energy Oil & Gas",
            "Engineering & Utilities",
            "Environmental Health & Safety",
            "Hospitality Tourism & Catering",
            "Human Resources",
            "Information Technology",
            "Legal",
            "Management",
            "Marine",
            "Marketing",
            "Medical Professionals & Healthcare",
            "Mining",
            "Procurement & Supply Chain Management",
            "Public Sector",
            "Publishing Media & Creative Arts",
            "Retailing Wholesaling & Purchasing",
            "Sales",
            "Telecoms",
            "Transport Shipping Warehousing & Automotive",
            "Travel & Airlines",
            "Working from Home",
        ],
    },
    {
        q: "Previous Employment status",
        type: "dropdown",
        option: [
            "None",
            "Full-time",
            "Part-time",
            "Self Employed",
            "Contractor",
            "Unemployed",
        ],
    },
    {
        q: "Previous Employment level",
        type: "dropdown",
        option: [
            "None",
            "Intern",
            "Entry-Level",
            "Junior",
            "Assistant Manager",
            "Manager",
            "Senior Manager",
            "Executive",
            "VP",
            "CEO",
            "Managing Director",
            "Board Member",
        ],
    },
    {
        q: "Years in previous position",
        type: "numeric",
        option: "",
    },
    {
        q: "Industry of previous employment",
        type: "dropdown",
        option: [
            "None",
            "Accountancy & Finance",
            "Actuary",
            "Agriculture",
            "Banking Financial services & Insurance",
            "Beauty Hair Care Leisure & Sport",
            "Construction Architecture & Property",
            "Customer Service Call Centres & Languages",
            "Development Social & Voluntary",
            "Education Childcare & Training",
            "Energy Oil & Gas",
            "Engineering & Utilities",
            "Environmental Health & Safety",
            "Hospitality Tourism & Catering",
            "Human Resources",
            "Information Technology",
            "Legal",
            "Management",
            "Marine",
            "Marketing",
            "Medical Professionals & Healthcare",
            "Mining",
            "Procurement & Supply Chain Management",
            "Public Sector",
            "Publishing Media & Creative Arts",
            "Retailing Wholesaling & Purchasing",
            "Sales",
            "Telecoms",
            "Transport Shipping Warehousing & Automotive",
            "Travel & Airlines",
            "Working from Home",
        ],
    },
    {
        q: "Previous Employment status",
        type: "dropdown",
        option: [
            "None",
            "Full-time",
            "Part-time",
            "Self Employed",
            "Contractor",
            "Unemployed",
        ],
    },
    {
        q: "Previous Employment level",
        type: "dropdown",
        option: [
            "None",
            "Intern",
            "Entry-Level",
            "Junior",
            "Assistant Manager",
            "Manager",
            "Senior Manager",
            "Executive",
            "VP",
            "CEO",
            "Managing Director",
            "Board Member",
        ],
    },
    {
        q: "Years in previous position",
        type: "numeric",
        option: "",
    },
    {
        q: "Industry of previous employment",
        type: "dropdown",
        option: [
            "None",
            "Accountancy & Finance",
            "Actuary",
            "Agriculture",
            "Banking Financial services & Insurance",
            "Beauty Hair Care Leisure & Sport",
            "Construction Architecture & Property",
            "Customer Service Call Centres & Languages",
            "Development Social & Voluntary",
            "Education Childcare & Training",
            "Energy Oil & Gas",
            "Engineering & Utilities",
            "Environmental Health & Safety",
            "Hospitality Tourism & Catering",
            "Human Resources",
            "Information Technology",
            "Legal",
            "Management",
            "Marine",
            "Marketing",
            "Medical Professionals & Healthcare",
            "Mining",
            "Procurement & Supply Chain Management",
            "Public Sector",
            "Publishing Media & Creative Arts",
            "Retailing Wholesaling & Purchasing",
            "Sales",
            "Telecoms",
            "Transport Shipping Warehousing & Automotive",
            "Travel & Airlines",
            "Working from Home",
        ],
    },
];
export const finantialQuestions = [
    { q: "How much are you planning to borrow?", type: "numeric", option: "" },
    {
        q: "How many months are you planning to take the loan for?",
        type: "numeric",
        option: "",
    },

    {
        q: "Will your loan be secured or unsecured?",
        type: "dropdown",
        option: ["Secured", "Unsecured"],
    },

    { q: "What is the value of the security?", type: "numeric", option: "" },

    {
        q: "Security Type",
        type: "dropdown",
        option: [
            "Financial Instruments",
            "Insurance Policy",
            "Motor Car",
            "Home",
            "Other",
        ],
    },
    {
        q: "Purpose of Loan",
        type: "dropdown",
        option: [
            "Education",
            "Medical Related",
            "Home Improvement",
            "Travel",
            "Other",
            "Debt Consolidation",
        ],
    },
    { q: "Monthly Credit Card Payment", type: "numeric", option: "" },
    { q: "Mortgage Payments", type: "numeric", option: "" },
    { q: "Car Loan Payments", type: "numeric", option: "" },
    { q: "Other Loan Payments", type: "numeric", option: "" },
    { q: "Rent Payment", type: "numeric", option: "" },
    { q: "How much do you spend on utilities?", type: "numeric", option: "" },
    { q: "Non-life Insurance Payment", type: "numeric", option: "" },
    {
        q: "Life Insurance Payments",
        type: "numeric",
        option: "",
    },
    { q: "Transport Expenses", type: "numeric", option: "" },
    { q: "Living Expenses", type: "numeric", option: "" },
    { q: "Education Expenses", type: "numeric", option: "" },
    { q: "Medical Expenses", type: "numeric", option: "" },
    { q: "Entertainment Expenses", type: "numeric", option: "" },
    { q: "Other Monthly Income", type: "numeric", option: "" },
    { q: "Net Monthly Income", type: "numeric", option: "" },
    { q: "Other Monthly Expenses", type: "numeric", option: "" },
    {
        q: "Have you ever been bankrupt?",
        type: "dropdown",
        option: ["Yes", "No"],
    },
    {
        q: "How many years have passed since your bankruptcy?",
        type: "numeric",
        option: "",
    },
];
